#!/bin/sh
flatpak install --system --bundle /usr/share/deepin-flatpak/app/com.deepin.Music/x86_64/master/bundle
rm /usr/share/deepin-flatpak/app/com.deepin.Music/x86_64/master/bundle
for f in `ls -d /home/*/`;
do
	mkdir -p $f/.var/app/com.deepin.Music/cache/;
	USER=`echo $f|cut -d '/' -f 3`;
	flatpak run -v --command=fc-cache com.deepin.Music -v
	cp -rf /root/.var/app/com.deepin.Music/cache/fontconfig/  $f.var/app/com.deepin.Music/cache/
	chown -R $USER:$USER $f
done

exit 0
